name: Test Matrix Function

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest, windows-2019, windows-latest, macos-12, macos-13, macos-latest]
        images: [hello-world, alpine]
    runs-on: ${{ matrix.os }}
    name: Run on ${{ matrix.os }} with image ${{ matrix.images }}
    steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run image ${{ matrix.images }} on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}
