name: Sequential Jobs with Cowsay

on:
  push:

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build step
        run: echo "Building the project..."

      - name: Install cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Cowsay Build Complete
        run: cowsay "Build job is complete!"

  test:
    name: Test Job
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: echo "Running tests..."

      - name: Install cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Cowsay Test Complete
        run: cowsay "Test job is complete!"

  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy step
        run: echo "Deploying the project..."

      - name: Install cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Cowsay Deploy Complete
        run: cowsay "Deploy job is complete!"
