name: download/upload artifactory

on:
 push 

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install cowsay program
      run: sudo apt-get insta;; cowsay -y 

    - name: Execute cowsay CMD
      run: cowsay -f dragon "run for cover, i am DRAGON..RAWR" >> dragon.txt

    - name: upload Dragon text file 
      uses: actions/upload-artifact@v4
      with:
        name: dragon-text-file
        path: dragon.txt

    - name: download Dragon text file 
      uses: actions/download-artifact@v4
      with:
        name: dragon-test-file